### ISSUE TITLE
The address listed apparently is not their current one.

### ISSUE THREAD

**Issue by joshytheprogrammer** [joshytheprogrammer/ochexagonv2#10]
This is my bad - apologies. I'll send you an image with the proper address.

![image](https://github.com/joshytheprogrammer/ochexagonv2/assets/102735414/a0a54bf6-d03c-45af-8db4-76e5132a32d8)

**Comment by RalphFred** [comment]
Done

**Comment by joshytheprogrammer** [comment]
The address placed there was not changed. Am I missing something? This is the second closed issue that has not been changed!!!![image](https://github.com/joshytheprogrammer/ochexagonv2/assets/102735414/63ac00da-c80f-4310-ad79-1e08dc2631cc)

**Comment by joshytheprogrammer** [comment]
I was wrong apologies. I was still checking the main.
